import { ScaledSheet } from "react-native-size-matters";



export const styles = ScaledSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff", overflow: "hidden", paddingBottom: "74@ms" },
  main: { marginHorizontal: "20@ms", marginBottom: "80@ms" },
  loaderContainer: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#fff" },
  loadingText: { marginTop: "10@vs", fontSize: "14@ms", color: "#75748E", fontFamily: "Poppins_500Medium" },
  title: {
    marginTop: "15@ms",
    fontFamily: "Poppins_600SemiBold",
    fontWeight: "600",
    fontSize: "21@ms",
    color: "#1B1919",
    lineHeight: "28@ms",
    marginBottom: "10@vs",
  },
  container: { padding: "1@ms", backgroundColor: "#fff" },
  image: { width: "100%", height: "230@ms", borderRadius: "10@ms" },
  times: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: "15@ms" },
  date: { fontFamily: "Poppins_500Medium", color: "#000", fontWeight: "500" },
  header: { fontFamily: "Poppins_600SemiBold", fontSize: "15@ms", fontWeight: "600", lineHeight: "26@ms", marginBottom: "5@ms" },
  nutri: { fontFamily: "Poppins_400Regular", fontWeight: "400", fontSize: "16@ms", lineHeight: "18@ms", color: "#000", marginBottom: "2@ms" },
  milk: { fontFamily: "Poppins_600SemiBold", fontWeight: "600", color: "#F63E4C" },
  learn: { marginTop: "10@ms", fontFamily: "Poppins_400Regular", color: "#75748E", fontWeight: "400", lineHeight: "20@ms" },
  keystore: { marginTop: "25@ms", borderWidth: 1, borderColor: "#E2E2E2", padding: "12@ms", borderRadius: "10@ms", backgroundColor: "#F9F9F9" },
  keystores: { marginTop: "25@ms", padding: "12@ms", borderRadius: "10@ms" },
  headers: { fontFamily: "Poppins_600SemiBold", fontSize: "16@ms", fontWeight: "600", color: "#1B1919", marginBottom: "10@ms" },
  appears: { fontFamily: "Poppins_400Regular", color: "#75748E", fontSize: "14@ms", lineHeight: "27@ms", marginBottom: "10@ms" },
  keys: { flexDirection: "row", justifyContent: "flex-start", alignItems: "flex-start", paddingVertical: "4@ms", marginBottom: "5@ms" },
  icon: { width: "13@ms", height: "18@ms", marginTop: "2@ms", marginRight: "8@ms", padding: "5@ms", tintColor: "#F63E4C" },
  icons: { width: "18@ms", marginTop: "2@ms", height: "18@ms", marginRight: "8@ms", tintColor: "#F63E4C" },
  first: { flexShrink: 1, fontFamily: "Poppins_500Medium", fontWeight: "500", fontSize: "14@ms", color: "#000", lineHeight: "20@ms" },
  second: { fontFamily: "Poppins_400Regular", fontWeight: "400", fontSize: "14@ms", color: "#75748E" },
  firsts: { fontFamily: "Poppins_400Regular", color: "#75748E", fontSize: "14@ms" },
  bottom: { fontFamily: "Poppins_400Regular", fontWeight: "400", fontSize: "14@ms", color: "#75748E", marginTop: "2@ms" },
  scrollContainer: { paddingBottom: "30@ms" ,backgroundColor:"#fff"},
  containers: { padding: "1@ms", marginTop: "20@ms" },
});